### ISSUE TITLE
Issues with puppet agent 6.8.0

### ISSUE THREAD

**Issue by trenta** [voxpupuli/puppet-nodejs#401]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.8.0
- Ruby:
- Distribution: Ubuntu 18.04 LTS
- Module version: 7.0.1

## How to reproduce (e.g Puppet code you use)
class { 'nodejs': }

## What are you seeing
Puppet runs are failing on machines after upgrade to puppet agent 6.8.0  correcting installation

## Output log
Notice: /Stage[main]/Nodejs::Install/Package[nodejs]/ensure: created (corrective)
Info: Package nodejs-dev is virtual, defaulting to nodejs
Notice: /Stage[main]/Nodejs::Install/Package[nodejs-dev]/ensure: removed (corrective)

## Any additional information you'd like to impart
I haven't looked into this very far yet but it's happening everywhere I use the module and puppet agent has been upgraded to 6.8.0

**Comment by Dan33l** [comment]
Hi @trenta thank you for the report.

It looks this issue is confirmed on all Ubuntu versions with Puppet 6 :
- with 1404 : https://travis-ci.org/voxpupuli/puppet-nodejs/jobs/577306111#L1558
- with 1604 : https://travis-ci.org/voxpupuli/puppet-nodejs/jobs/577306113#L1511
- with 1804 : https://travis-ci.org/voxpupuli/puppet-nodejs/jobs/577306115#L1509

All others pass acceptance tests:
https://travis-ci.org/voxpupuli/puppet-nodejs/builds/577306105

Can you investigate what is special with Ubuntu and Puppet 6 ?

**Comment by trenta** [comment]
I may get time.  I wasn't effected by this when all puppet agents where 6.7.2

**Comment by trenta** [comment]
Actually I think the puppet 6.8.0 release notes show the issue.  https://puppet.com/docs/puppet/latest/release_notes_puppet.html#virtual-packages-support-for-apt-dpkg
Specifically the virtual package support.  See the output line from a puppet run.

```
Notice: /Stage[main]/Nodejs::Install/Package[nodejs]/ensure: created (corrective)
Info: Package nodejs-dev is virtual, defaulting to nodejs
Notice: /Stage[main]/Nodejs::Install/Package[nodejs-dev]/ensure: removed (corrective)
```

**Comment by Dan33l** [comment]
Ah yes probably.

@trenta can you propose a PR ?

**Comment by Dan33l** [comment]
This bug will probably be resolved by next release of puppet-agent:
https://tickets.puppetlabs.com/browse/PA-2402?focusedCommentId=680864#comment-680864

**Comment by trenta** [comment]
Yes I just saw that this morning.  https://puppet.com/docs/puppet/latest/release_notes_puppet.html#puppet-resolved-issues-x.8.1

I've updated and tested and this problem is fixed.
